-- Table structure for table `inventory`

-- CREATE TABLE public.inventory 
-- (
--     inventory_id INT GENERATED BY DEFAULT AS IDENTITY,
--     inventory_name CHARACTER VARYING NOT NULL,
--     inventory_description CHARACTER VARYING NOT NULL,
--     inventory_price NUMERIC(10,2) NOT NULL,
--     inventory_quantity INT NOT NULL,
--     classification_id INT NOT NULL,
--     CONSTRAINT inventory_pk PRIMARY KEY (inventory_id),
--     CONSTRAINT inventory_fk FOREIGN KEY (classification_id) REFERENCES public.classification (classification_id)
-- );



-- Table structure for table `inventory`

CREATE TABLE IF NOT EXISTS public.inventory
(
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id),
);


